# -*- conf -*-
shell=/usr/bin/bash
app-id=foot
title=foot
font=Hack Nerd Font:size=9:style=Bold
dpi-aware=yes
bold-text-in-bright=yes

[main]
include=/usr/share/foot/themes/rose-pine

[bell]
urgent=no
notify=no

[desktop-notifications]
command=notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}

[scrollback]
lines=10000

[cursor]
style=block
blink=yes

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

[search-bindings]
cancel=Control+g Control+Shift+c Escape

[url-bindings]
cancel=Control+g Control+Shift+c Control+d Escape
