# -*- conf -*-
shell=/usr/bin/bash
app-id=foot
title=foot
font=Iosevka Nerd Font:size=10:weight=bold
dpi-aware=yes
bold-text-in-bright=yes

[main]
include=/usr/share/foot/themes/rose-pine

[bell]
urgent=no
notify=no

[colors]
alpha=1.0

[scrollback]
lines=10000

[cursor]
style=block
blink=yes

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

[search-bindings]
cancel=Control+g Control+Shift+c Escape

[url-bindings]
cancel=Control+g Control+Shift+c Control+d Escape
