# --- User environment variables ---
# Editors
EDITOR=nvim
# Set sudo editor, i.e., sudo -e
SUDO_EDITOR=nvim
# Set full-screen editor
VISUAL=nvim

# Pager (less, bat)
LESS="-RFMX --mouse --wheel-lines=3"
BAT_PAGER="less"
PAGER="bat --paging=always"
GIT_PAGER="bat --paging=always"

# Bat configuration
BAT_STYLE="header,grid"
BAT_THEME=ansi
