SYSTEM_UTILS=(
    trash-cli
    fastfetch
    reflector
    wl-clipboard
)


DEV_TOOLS=(
    fd
    fzf
    bat
    zsh
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
    podman
    podman-docker
    docker-compose
    breeze-gtk
    less
    tree
    ripgrep
    zoxide
    wget
    stow
    gcc
    vim
    code
    vivaldi
    nvim
    spotify-launcher
    openssh
)

FONTS {
    ttf-jetbrains-mono-nerd
    noto-fonts
    ttf-roboto

}

MAINTENANCE=(
    pacman-contrib
)
