SYSTEM_UTILS=(
    trash-cli
    fastfetch
    reflector
    wl-clipboard
)


DEV_TOOLS=(
    fd
    fzf
    bat
    zsh
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
    docker
    docker-compose
    kubeadm
    kubelet
    kubectl
    minikube
    breeze-gtk
    less
    tree
    ripgrep
    zoxide
    wget
    stow
    gcc
    vim
    code
    vivaldi
    nvim
    spotify-launcher
    openssh
)

PROG_LANG=(
    python
    python-pip
    npm
    nodejs
)

FONTS=(
    ttf-jetbrains-mono-nerd
    ttf-roboto
    noto-fonts
    noto-fonts-emoji
)

MAINTENANCE=(
    pacman-contrib
)
