SYSTEM_UTILS=(
    trash-cli
    fastfetch
)


DEV_TOOLS=(
    fd
    fzf
    bat
    zsh
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
    less
    tree
    ripgrep
    zoxide
    wget
    stow
    gcc
    vim
)

MAINTENANCE=(
    pacman-contrib
)
