SYSTEM_UTILS=(
    7zip
    man-db
    man-pages
    trash-cli
    logrotate
    ufw
    reflector
    btrfs-assistant
    snap-pac
    wl-clipboard
    fprintd
    fastfetch
)

NVIDIA=(
    nvidia-prime
)

DEV_TOOLS=(
    fd
    fzf
    bat
    zsh
    git
    docker
    docker-compose
    podman
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
    less
    tree
    ripgrep
    zoxide
    wget
    stow
    gcc
    neovim
    distrobox
    code
    vivaldi
    python-pip
    npm
    opencode
)

MAINTENANCE=(
    pacman-contrib
)

DESKTOP=(
    libreoffice-still
    gwenview
    partitionmanager
)

PROG_LANGS=(
    python
    nodejs
)

MEDIA=(
    mpv
)

FONTS=(
    ttf-jetbrains-mono-nerd
    ttf-roboto
)

SERVICES=(
    ufw
    systemd-resolved
    docker
    paccache.timer
    logrotate
    smartd
)

NVIDIA_SERVICES=(
    nvidia-persistenced
)
