DEV_TOOLS=(
    ranger
    neovim
    fastfetch
    podman-compose
    podman
    distrobox
    git
    stow
    btop
)

DESKTOP=(
    niri
    noctalia
    imv
    brightnessctl
    zathura
    zathura-pdf-poppler
)

