SYSTEM_UTILS=(
    man-db
    man-pages
    logrotate
    reflector
    btrfs-assistant
    wl-clipboard
    fprintd
    fastfetch
    sbctl
    pkgstats
    solaar
    dosfstools
    )

NVIDIA=(
    nvidia-prime
    )

DEV_TOOLS=(
    fd
    fzf
    bat
    git
    docker
    docker-compose
    podman
    less
    tree
    ripgrep
    zoxide
    wget
    stow
    neovim
    distrobox
    code
    vivaldi
    opencode
    yazi
    )

MAINTENANCE=(
    pacman-contrib
    )

DESKTOP=(
    libreoffice-still
    gwenview
    partitionmanager
    spotify-launcher
    plasma-meta
    )

VIRT_MAN=(
    qemu-full
    libvirt
    virt-manager
    dnsmasq
    ebtables
    iptables-nft
    ovmf
    swtpm
    )

MEDIA=(
    mpv
    )

FONTS=(
    ttf-jetbrains-mono-nerd
    )

SERVICES=(
    systemd-resolved
    docker
    paccache.timer
    logrotate
    smartd
    )

NVIDIA_SERVICES=(
    nvidia-persistenced
    )
